### ISSUE TITLE
Rice and Stones  #2

### ISSUE THREAD

**Issue by AeishnaKhaund** [SEDSCelestiaBPGC/Externally-Randomized-Encryption-Service#11]
- Use an OpenCV funtionality (or any other image processing library) to detect the centers of the black spots (stones/marbles) in the preprocessed image (see #3 or files in the Rice and Stones folder). 
- Convert the coordinates of the centers into binary numbers.
- Store the binary numbers digit by digit into a one-dimensional array to construct the random sequence.

**Comment by Goku2699** [comment]
The two photos will have two different approaches for finding the centers of contours so should we develop an ml/dl model to do it or two different codes to do it?

**Comment by Bluish-y** [comment]
Hey Goku, I am also working with the @SEDSCelestiaBPGC/eres-core and will answer questions when I can.
The image of the larger contours was not optimal because of noise during preprocessing, and we will mostly be working with images like the one with the smaller blobs (they need not necessarily be small, but the blob to noise ratio is similar to that picture). So try to work with that image.
